### ISSUE TITLE
抠图后的图片比较模糊

### ISSUE THREAD

**Issue by cstybbt** [SprInec/PortraitCutout#1]
哪里可以修改输出图像清晰度的参数？

**Comment by SprInec** [comment]
抠图后的图片应该是和原图的分辨率一致的。
该软件没有可以调整图像清晰度的设置，不过你可以在Scripts/backend.py中添加相关调整分别率的代码，在EventProcress._save前级进行分别率调整就行

**Comment by SprInec** [comment]
抠图后的图片应该是和原图的分辨率一致的。
该软件没有可以调整图像清晰度的设置，不过你可以在Scripts/backend.py中添加相关调整分辨率的代码，确保在EventProcress._save前级进行分辨率修改就行
